// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kawabatas/m-bank/domain/repository (interfaces: PaymentTransactionRepository)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/kawabatas/m-bank/domain/model"
)

// MockPaymentTransactionRepository is a mock of PaymentTransactionRepository interface.
type MockPaymentTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentTransactionRepositoryMockRecorder
}

// MockPaymentTransactionRepositoryMockRecorder is the mock recorder for MockPaymentTransactionRepository.
type MockPaymentTransactionRepositoryMockRecorder struct {
	mock *MockPaymentTransactionRepository
}

// NewMockPaymentTransactionRepository creates a new mock instance.
func NewMockPaymentTransactionRepository(ctrl *gomock.Controller) *MockPaymentTransactionRepository {
	mock := &MockPaymentTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockPaymentTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentTransactionRepository) EXPECT() *MockPaymentTransactionRepositoryMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockPaymentTransactionRepository) Cancel(arg0 context.Context, arg1 string) (*model.PaymentTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", arg0, arg1)
	ret0, _ := ret[0].(*model.PaymentTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cancel indicates an expected call of Cancel.
func (mr *MockPaymentTransactionRepositoryMockRecorder) Cancel(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockPaymentTransactionRepository)(nil).Cancel), arg0, arg1)
}

// Confirm mocks base method.
func (m *MockPaymentTransactionRepository) Confirm(arg0 context.Context, arg1 string) (*model.PaymentTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", arg0, arg1)
	ret0, _ := ret[0].(*model.PaymentTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Confirm indicates an expected call of Confirm.
func (mr *MockPaymentTransactionRepositoryMockRecorder) Confirm(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockPaymentTransactionRepository)(nil).Confirm), arg0, arg1)
}

// Get mocks base method.
func (m *MockPaymentTransactionRepository) Get(arg0 context.Context, arg1 string) (*model.PaymentTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*model.PaymentTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPaymentTransactionRepositoryMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPaymentTransactionRepository)(nil).Get), arg0, arg1)
}

// Try mocks base method.
func (m *MockPaymentTransactionRepository) Try(arg0 context.Context, arg1 string, arg2 uint, arg3 int) (*model.PaymentTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Try", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*model.PaymentTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Try indicates an expected call of Try.
func (mr *MockPaymentTransactionRepositoryMockRecorder) Try(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Try", reflect.TypeOf((*MockPaymentTransactionRepository)(nil).Try), arg0, arg1, arg2, arg3)
}
